### ISSUE TITLE
支持自动生成注解和单元测试吗？

### ISSUE THREAD

**Issue by cloudhu** [aixcoder-plugin/aiXcoder-7B#11]
其他代码辅助的大模型有这些功能，还可以自动生成API文档。

**Comment by YoctoHan** [comment]
我们开源的这一版本是Base模型，尚未支持这些功能，您可以下载体验我们的插件，在各大IDE的插件市场均可找到，也可以在README中找到下载链接，社区版插件有您提到的这些功能，感谢您关注，欢迎您分享您的使用体验。

**Comment by cloudhu** [comment]
好的，谢谢
