### ISSUE TITLE
补全如何使用

### ISSUE THREAD

**Issue by mayubin258** [aixcoder-plugin/aiXcoder-7B#14]
我看了下你的 sess_huggingface.py文件，我的需求是想做一个代码补全的demo，但是发现回复的内容太多，我在思考是否跟input_wrapper提供的参数设置有关系
调用例子如以下：
"code_string": "The programming language I am using is Java. I only need you to complete the possible code that may be written at the end of my code, without providing any extra explanation or description. Please directly complete the code for your response field. If it cannot be processed, return an empty string. The current code is public static void main(String[] args) {\n SpringApplication application \u003d new SpringApplication(TranCoderApplication.class);\n application.addInitializers(SpringBeanUtil::setApplicationContext);\n spring."
我希望接口返回run(args);
但是实际接口返回：
 
  # the file path is: test.py
# the code file is written by Python
The programming language I am using is Java. I only need you to complete the possible code that may be written at the end of my code, without providing any extra explanation or description. Please directly complete the code for your response field. If it cannot be processed, return an empty string. The current code is public static void main(String[] args) {
 SpringApplication application = new SpringApplication(TranCoderApplication.class);
 application.addInitializers(SpringBeanUtil::setApplicationContext);
 spring.application.run(args);
 }

Assistant: 

 public static void main(String[] args) {
   SpringApplication application = new SpringApplication(TranCoderApplication.class);
   application.addInitializers(SpringBeanUtil::setApplicationContext);
   spring.application.run(args);
 }

**Comment by HoratioJSY** [comment]
按照您的描述，输入需要构造成如下形式，其中`code_string` 表示光标之前的代码文本，`later_code`表示光标之后的代码文本（可能为空），然后期待模型预测出光标所在文本。您如果需要指定语言，可以在`path`变量传入一个伪造的Java名字，例如`test.java`，但是`path`变量最好是从真实项目到当前文件的完整路径，并且符合编程语言的要求，例如java中要求文件名与类名一致。

```
text = input_wrapper(
    code_string="public static void main(String[] args) {\n SpringApplication application \u003d new SpringApplication(TranCoderApplication.class);\n application.addInitializers(SpringBeanUtil::setApplicationContext);\n spring.",
    later_code="",
    path="test.java"
)
```

最终推理脚本会将输入与输出都打印出来，您也可以自行截断只保留输出结果：

```
<AIX-SPAN-PRE> <AIX-SPAN-POST> <AIX-SPAN-MIDDLE> // the file path is: test.java
// the code file is written by Java
public static void main(String[] args) {
 SpringApplication application = new SpringApplication(TranCoderApplication.class);
 application.addInitializers(SpringBeanUtil::setApplicationContext);
 spring.run(args);
}</s>
```

**Comment by mayubin258** [comment]
感谢大佬百忙之中回答~~
是这样，如果我根据结果再加工（如截断之类）我怕和真实代码有所冲突，能否通过再prompt做手脚让他只输出补全手段呢
比如：
{
  code_string:"public static void main(String[] args) {
  SpringApplication application = new SpringApplication(TranCoderApplication.class);
  application.addInitializers(SpringBeanUtil::setApplicationContext);
  spring.application."
  later_code="",
  path="test.java"
}
我希望能只给出后续补全结果，如
.run(args);

**Comment by HoratioJSY** [comment]
将输入与输出拼起来作为模型输出来是Huggingface transformers 库的一个行为，和输入的拼接并没有关系。如果您只想输出 `.run(args);`，那么首先需要告诉模型光标下文已经有了一个花括号，模型只需要预测花括号里面的内容就行，因此 `later_code="\n}"`。其次，需要数输入的Token数需要数出来，以便解码的时候将输出token截断。以下是示例代码：

```python
import torch
import sys
from hf_mini.utils import input_wrapper
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda" # the device to load the model onto

tokenizer = AutoTokenizer.from_pretrained("aiXcoder/aixcoder-7b-base")
model = AutoModelForCausalLM.from_pretrained("aiXcoder/aixcoder-7b-base", torch_dtype=torch.bfloat16)


text = input_wrapper(
    code_string="public static void main(String[] args) {\n SpringApplication application \u003d new SpringApplication(TranCoderApplication.class);\n application.addInitializers(SpringBeanUtil::setApplicationContext);\n spring.",
    later_code="\n}",
    path="test.java"
)

if len(text) == 0:
    sys.exit()

inputs = tokenizer(text, return_tensors="pt", return_token_type_ids=False)

inputs = inputs.to(device)
inputs_len = len(inputs["input_ids"][0])
model.to(device)

outputs = model.generate(**inputs, max_new_tokens=256)
results = tokenizer.decode(outputs[0][inputs_len:], skip_special_tokens=True)
print(results)


```

**Comment by mayubin258** [comment]
thanks~

**Comment by mechigonft** [comment]
你好，请问下，code_string和later_code的输入长度有限制吗？

**Comment by HoratioJSY** [comment]
可以查看这个Issue：https://github.com/aixcoder-plugin/aiXcoder-7B/issues/21

**Comment by mayubin258** [comment]
你好，我最近遇到一个问题，还是多行问题
如输入参数如下
{
  "code_string": "public AccountVO tryAcquire(){\nint pooSize = accountPool.size",
   "later_code": "\n}",
    "path":"test.java"
}

模型返回
();
if(pooSize == 0)
return null;
AccountVO account = accountPool.get(0);
accountPool.remove(0);
return account;

但是其实我还是只要第一行的“();”，后面的不需要，这样有办法统一从入参做处理
