### ISSUE TITLE
Can I configure the JetBrains plugin to point to a locally self-hosted aiXcoder model?

### ISSUE THREAD

**Issue by zzlian** [aixcoder-plugin/aiXcoder-7B#15]
I have deployed an aiXcoder model locally, but when using the aiXcoder plugin, I noticed that it requires me to log in. After a successful login, I couldn't find an option to configure the plugin to point to my self-hosted aiXcoder model. Is there a way to set the plugin to use a locally deployed model? Or are there any plans to introduce this configuration option in the future? Many thanks!

**Comment by HoratioJSY** [comment]
Sorry, we currently do not support plugin-side integration with locally deployed models, as the aiXcoder plugin requires a corresponding server-side component. At the moment, we do not have plans to open source either the plugin-side or the server-side components. You may refer to open source server-side solutions in the text generation domain, as well as open source code plugins, to set up the complete service.

**Comment by 01hrithik** [comment]
Yes, you can configure the JetBrains plugin to point to a locally self-hosted aiXcoder model. Here are the steps to do so:

1. First, you need to download the server package for your operating system from the aiXcoder GitHub repository.

2. Once downloaded, extract the contents of the package to the appropriate directory. The directories for each operating system are as follows:

Windows: %UserProfile%\aiXcoder\installer\localserver\current\server
Mac OS X: ~/Library/Application Support/aiXcoder/installer/localserver/current/server
Linux: ~/aiXcoder/installer/localserver/current/server

3. After extracting the contents, you can configure the plugin to point to the local server.

For JetBrains IDEs, you can follow these steps:

1. Go to File > Settings (on Windows/Linux) or IntelliJ IDEA > Preferences (on Mac OS X).

2. Navigate to Build, Execution, Deployment > Deployment.

3. Click on the + button and select Local or mounted folder.

4. In the Create new server dialog, enter a name for the server and click OK.

5. In the Connection tab, specify the server configuration root folder and the URL address to access it.

6. In the Mappings tab, set correspondence between the project root folder, the folder on the server to copy the data from the project root folder to, and the URL address to access the copied data on the server.

For Eclipse, you can follow these steps:

1. Copy the downloaded JAR file to the dropins folder under Eclipse's installation folder.

2. Open the Preferences window and navigate to AIxCoder.

3. Under Server URL, enter the URL address of your locally self-hosted aiXcoder model.

Please note that the exact steps may vary depending on the JetBrains IDE  you are using.

**Comment by Paula1990x** [comment]
bc1qnx47enc98tg4yvuyudaf9axg6ckjl844w6f6rf

**Comment by ManasiRoy** [comment]
Yes, you can configure the JetBrains plugin to point to a locally self-hosted aiXcoder model. First, ensure your aiXcoder model is running locally and accessible. Then, in the JetBrains plugin settings, locate the section related to aiXcoder or code completions. Within this section, there should be an option to specify the endpoint or URL of the aiXcoder model. Enter the address of your locally hosted aiXcoder model here. Ensure that the port and any authentication details are correctly configured to match your setup. Save the settings, and the JetBrains plugin should now utilize your self-hosted aiXcoder model for code suggestions and completions.

**Comment by sinopec** [comment]
> Sorry, we currently do not support plugin-side integration with locally deployed models, as the aiXcoder plugin requires a corresponding server-side component. At the moment, we do not have plans to open source either the plugin-side or the server-side components. You may refer to open source server-side solutions in the text generation domain, as well as open source code plugins, to set up the complete service.

So, if u rwant to use it really locally ,u have to develop a totally new server  and IDE plugin ....
