### ISSUE TITLE
请问你们的数据集fim-extended具体怎么测的会开源吗？我拿这份数据测了下Exact Match和你们的report结果相差甚远啊

### ISSUE THREAD

**Issue by sinsauzero** [aixcoder-plugin/aiXcoder-7B#16]
deepseek 7B 的EM结果平均只有10多分，但是santacoder的数据结果和report的差不多

**Comment by HoratioJSY** [comment]
我们猜测是解码方式与后处理方式不一致，导致测得的结果比report低。我们再评测所有模型的时候都是 argmax 解码，最大序列长度设置为16K，最大生成长度为512，构造的输入格式为PSM。然后生成出来的字符串会做 strip()，去掉首位的空白字符，然后再对比GroundTruth。这份评测数据是一个初版，评测数据与评测方法我们都会做进一步的整理，后续再一同开源出来。

**Comment by sinsauzero** [comment]
你们也是将模型输出的全部内容和GT去做完全匹配吧（strip())后，完全相等才算正确？

**Comment by sinsauzero** [comment]
> 我们猜测是解码方式与后处理方式不一致，导致测得的结果比report低。我们再评测所有模型的时候都是 argmax 解码，最大序列长度设置为16K，最大生成长度为512，构造的输入格式为PSM。然后生成出来的字符串会做 strip()，去掉首位的空白字符，然后再对比GroundTruth。这份评测数据是一个初版，评测数据与评测方法我们都会做进一步的整理，后续再一同开源出来。


你们也是将模型输出的全部内容和GT去做完全匹配吧（strip())后，完全相等才算正确？

**Comment by sinsauzero** [comment]
应该没有做其它的后处理吧

**Comment by HoratioJSY** [comment]
对，是这样的，去掉字符串首尾的空白字符再对比，除此外没有后处理了

**Comment by sinsauzero** [comment]
嗯，生成配置都一致的。但是确实最终测的结果大相径庭。可能确实需要等后续你们更新评测方法吧

**Comment by sinsauzero** [comment]
哦解决了，你们的题目比较长。prompt_length得弄大点.
