### ISSUE TITLE
sess_megatron.py 这个类中，如果要改成可多并发而且是流式输出的应该怎么写

### ISSUE THREAD

**Issue by lwinhong** [aixcoder-plugin/aiXcoder-7B#20]
sess_megatron.py 这个类中，如果要改成可多并发而且是流式输出的应该怎么写

看到def run_infer(）函数有一个while True: 循环收集数据

**Comment by HoratioJSY** [comment]
def run_infer() 函数里面的 while True 会持续生成 Token，直到到达终止条件，随后将累计的ID序列解码成字符串，并在不同GPU中同步最终结果，然后 return。如果需要改成流式，可以利用Generator，即将 return 那部分逻辑改成 yield 逻辑。现在模型推理代码只能做batch_size层面的并行，如果要做高性能并发，可以参考 "[Batching Techniques for LLMs](https://arxiv.org/abs/2309.06180)" 部分的技术，动态地将新加入的请求加入批量推理过程。当然，您也可以参考 Huggingface 的TGI模块，快速地使用现有的轮子做高效推理，它能满足您的这两个要求。

**Comment by umeshyadav7988** [comment]
The `run_infer()` function continuously generates tokens within a `while True` loop until a termination condition is met. Subsequently, it decodes the accumulated ID sequence into a string, synchronizes the final result across different GPUs, and then returns it. If you want to make it streamable, you can utilize a generator by converting the logic inside the function from `return` to `yield`. Currently, the model inference code can only parallelize at the batch_size level. To achieve high-performance concurrency, you can refer to the techniques mentioned in the "Batching Techniques for LLMs" section, dynamically adding newly incoming requests to the batch inference process. Alternatively, you can also consider using Huggingface's TGI module, which allows for efficient inference and meets both of your requirements quickly by leveraging existing tools.

**Comment by lwinhong** [comment]
> def run_infer() 函数里面的 while True 会持续生成 Token，直到到达终止条件，随后将累计的ID序列解码成字符串，并在不同GPU中同步最终结果，然后 return。如果需要改成流式，可以利用Generator，即将 return 那部分逻辑改成 yield 逻辑。现在模型推理代码只能做batch_size层面的并行，如果要做高性能并发，可以参考 "[Batching Techniques for LLMs](https://arxiv.org/abs/2309.06180)" 部分的技术，动态地将新加入的请求加入批量推理过程。当然，您也可以参考 Huggingface 的TGI模块，快速地使用现有的轮子做高效推理，它能满足您的这两个要求。

感谢

**Comment by lwinhong** [comment]
> The `run_infer()` function continuously generates tokens within a `while True` loop until a termination condition is met. Subsequently, it decodes the accumulated ID sequence into a string, synchronizes the final result across different GPUs, and then returns it. If you want to make it streamable, you can utilize a generator by converting the logic inside the function from `return` to `yield`. Currently, the model inference code can only parallelize at the batch_size level. To achieve high-performance concurrency, you can refer to the techniques mentioned in the "Batching Techniques for LLMs" section, dynamically adding newly incoming requests to the batch inference process. Alternatively, you can also consider using Huggingface's TGI module, which allows for efficient inference and meets both of your requirements quickly by leveraging existing tools.

thanks
