### ISSUE TITLE
普通问答模式的prompt应该怎么包装

### ISSUE THREAD

**Issue by lwinhong** [aixcoder-plugin/aiXcoder-7B#23]
在源码中 input_wrapper 可以很好的包装代码生成prompt。
![image](https://github.com/aixcoder-plugin/aiXcoder-7B/assets/31954501/fae652ca-9935-4614-b8d5-78a8b6fe5d0a)

1.请问普通问答模式的**prompt**应该怎么包装？像chatgtp那样问答
   例如： 
   Q：请使用C#生成一个快速排序算法
   A：xxxx

2.发现一个问题，就是代码生成完成之后的末尾，最后都会带上一个</s>
![image](https://github.com/aixcoder-plugin/aiXcoder-7B/assets/31954501/da994d14-9d98-4402-a85b-8c9a4d8f6bd6)

**Comment by YoctoHan** [comment]
您好，当前开源的模型为Base模型，没有进行对话的能力，但是如果您想要进行服务化的部署进行QA，可以尝试用prompt引导模型让其认为自己在续写一份markdown，用您提到的问题进行举例：
Q：# 以下是利用C#生成的一个快速排序算法
虽然这样的形式并非常见的QA模式，但是这样包装可以让模型输出比直接提问效果更好的答案。

您提到的第二个问题，是表示文字部分结束的特殊符号，模型生成这个符号后会停止当次预测。

**Comment by lwinhong** [comment]
> 您好，当前开源的模型为Base模型，没有进行对话的能力，但是如果您想要进行服务化的部署进行QA，可以尝试用prompt引导模型让其认为自己在续写一份markdown，用您提到的问题进行举例： Q：# 以下是利用C#生成的一个快速排序算法 虽然这样的形式并非常见的QA模式，但是这样包装可以让模型输出比直接提问效果更好的答案。
> 
> 您提到的第二个问题，是表示文字部分结束的特殊符号，模型生成这个符号后会停止当次预测。

1.不需要任何包装，直接这样提问吗  **Q：# 以下是利用C#生成的一个快速排序算法**
2.那个停止符自己写代码去除了

> ····当前开源的模型为Base模型，没有进行对话的能力····  ， 有chat能力的模型后面会开源有吗

**Comment by YoctoHan** [comment]
1.不需要任何包装，直接这样提问吗 Q：# 以下是利用C#生成的一个快速排序算法
您上面的这个提问方式是可以的，也是比较推荐的。

2.有chat能力的模型后面会开源有吗？
会有的，我们正在积极推进这些事，等到本地的测试和调整结束后就会和大家见面。

**Comment by lwinhong** [comment]
> 1.不需要任何包装，直接这样提问吗 Q：# 以下是利用C#生成的一个快速排序算法 您上面的这个提问方式是可以的，也是比较推荐的。
> 
> 2.有chat能力的模型后面会开源有吗？ 会有的，我们正在积极推进这些事，等到本地的测试和调整结束后就会和大家见面。

谢谢
