### ISSUE TITLE
怎么实现vscode本地代码补全

### ISSUE THREAD

**Issue by lingyezhixing** [aixcoder-plugin/aiXcoder-7B#28]
本地部署怎么进行vscode的代码补全？有推荐的插件吗？应该使用7B-base模型还是7B模型？

**Comment by HoratioJSY** [comment]
aiXcoder-7B-base 和 aiXcoder-7B 都能支持代码补全，但本项目只提供推理脚本，并不提供开源的插件与服务端，因此不能直接本地部署，可能需要开发者自行开发。
