### ISSUE TITLE
关于 CrossCodeEval 测试的问题

### ISSUE THREAD

**Issue by yfzhou3993** [aixcoder-plugin/aiXcoder-7B#37]
你好：
        请问在 CrossEvalCode 测试集上的测试结果，是否是依照测试集提供的提示和上下文构造方法测试的呢？
        我看在文章中提到其中另含了标准化的类的定义。

> The top 5
matches, capped at 512 tokens, are added to the prompt, along
with formatted class definitions from other files.

**Comment by HoratioJSY** [comment]
我们是用 crosscodeeval 的标准方式推理的，将检索的代码块以注释的方式贴到代码上文。论文中的描述是一个我们的误理解， 理解为crosscodeeval数据如同其论文中图 3 所示存在函数抽象信息。

**Comment by yfzhou3993** [comment]
感谢回复！

我也在aiXcoder上尝试测试了 crosscodeeval，但是我测的结果似乎不准确，结果如下：
||Java-EM|Java-ES|
|-------|-------|-------|
|aiXcoder-7B|11.36|59.6|
|aiXcoder-7B + BM25|19.96|64.88|
|aiXcoder-7B + BM25 w/ Ref.|22.25|66.33|

我使用的checkpoint文件，来自 https://huggingface.co/aiXcoder/aixcoder-7b
其中权重文件 pytorch_model-00001-of-00001.bin 的MD5值为 235b50360c66c25560172fdcd1c42913

测试代码来自 crosscodeeval github repo，地址是 https://github.com/amazon-science/cceval
测试配置为
```
set -e

export gpus=4
export CUDA_VISIBLE_DEVICES=1,2,3,4
export model=/mnt/checkpoint/aixcoder-7b/huggingface/aixcoder-7b
export language=java
model_max_tokens=32768
crossfile_max_tokens=512

task=line_completion
output_dir=${model}/${language}-${task}
mkdir -p $output_dir
python ../../scripts/vllm_inference.py \
  --tp $gpus \
  --task $task \
  --language $language \
  --model $model \
  --output_dir $output_dir \
  --data_root_dir ../../data \
  --model_max_tokens ${model_max_tokens} \
  --crossfile_max_tokens ${crossfile_max_tokens} 2>&1 | tee -a ${output_dir}/inference.log

/bin/bash ./default_eval.sh $language $task $output_dir

for task in line_completion_oracle_bm25 line_completion_rg1_bm25 line_completion_oracle_bm25
do
        output_dir=${model}/${language}-${task}
        mkdir -p $output_dir
        python ../../scripts/vllm_inference.py \
          --tp $gpus \
          --task $task \
          --language $language \
          --model $model \
          --output_dir $output_dir \
          --use_crossfile_context \
          --data_root_dir ../../data \
          --model_max_tokens ${model_max_tokens} \
          --crossfile_max_tokens ${crossfile_max_tokens} 2>&1 | tee -a ${output_dir}/inference.log

        /bin/bash ./default_eval.sh $language $task $output_dir
done
```

请问，是不是我的配置或者模型和论文中使用的有偏差呢

**Comment by HoratioJSY** [comment]
有两个需要确定的点，1. 模型权重我们在论文中测的是[https://huggingface.co/aiXcoder/aixcoder-7b-base](https://huggingface.co/aiXcoder/aixcoder-7b-base)，2.上下文拼接方式是不是和我们脚本中FIM的拼接方式是一致的：[https://github.com/aixcoder-plugin/aiXcoder-7B/blob/main/sess_huggingface.py#L12](https://huggingface.co/aiXcoder/aixcoder-7b-base)
