### ISSUE TITLE
[New Feature] Training code for training or finetuning on private dataset and APIs and Other Language (C# etc.)

### ISSUE THREAD

**Issue by bing0037** [aixcoder-plugin/aiXcoder-7B#5]
Thanks for the excellent work. Waiting for the update!

**Comment by YoctoHan** [comment]
We will update the fine-tuning script in the near future, but the open source of large-scale training method is very low priority, fine-tuning script you can check [#3 ](https://github.com/aixcoder-plugin/aiXcoder-7B/issues/3). Our model and community-edition plugins are supported C# currently , we will soon add a list of supported languages in the README. You can also try our plugins C# completion to see if it meets your needs.
