### ISSUE TITLE
支持使用vllm推理吗？

### ISSUE THREAD

**Issue by Virtual1257** [aixcoder-plugin/aiXcoder-7B#6]
目前aixcoder7b支持使用vllm加速推理吗？

**Comment by YoctoHan** [comment]
我们尝试过使用vllm进行加载和推理，是可以正常运行的。

**Comment by Virtual1257** [comment]
使用vllm推理，prompt使用input_wrapper包装一下就可以吗？补全和代码填空都用input_wrapper包装吗？

**Comment by YoctoHan** [comment]
之前为了调研提升吞吐量的手段简单测试过这个框架，我理解只需要使用input_wrapper包装一下prompt就可以喂给模型进行推理。

**Comment by hcbr** [comment]
> 我们尝试过使用vllm进行加载和推理，是可以正常运行的。

请问下prompt是怎么包装的？
我这边改造input_wrapper

![Image](https://github.com/user-attachments/assets/ee55dd6e-a08c-4a7d-be37-1b14537998ad)

会多出现一个token_id 25558  导致生成结果不对。
可以简单实验:

![Image](https://github.com/user-attachments/assets/325be186-b65f-4b5e-9feb-4c49c1133f75)
结果为：

![Image](https://github.com/user-attachments/assets/0f60752d-461f-438c-8bcb-eb161b80c863)
