### ISSUE TITLE
可以请教一下用什么工具实现语法检查和静态分析的吗

### ISSUE THREAD

**Issue by Strive-for-excellence** [aixcoder-plugin/aiXcoder-7B#8]
可以请教一下用什么工具实现语法检查和静态分析的吗，可否开源一些脚本，非常感谢

**Comment by HoratioJSY** [comment]
语法分析可以根据需求使用常见的 Parser，比如针对 Java 语言可以尝试 JavaParser 等工具，针对 Python 语言可以使用 ast 库等等，静态分析方面可以关注诸如南京大学的开源项目太阿等。关于数据处理与预训练任务构造的具体实现的程序，我们暂时不会开源相关代码。

**Comment by Strive-for-excellence** [comment]
好的，非常感谢！
